"""Increase password_hash length

Revision ID: 206b2e7a4125
Revises: ad53a219cf8a
Create Date: 2025-06-25 00:46:25.115776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206b2e7a4125'
down_revision = 'ad53a219cf8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
